query GetAdminArea($id: ID!, $adminLevel: Int!, $tolerance: Float) {
  adminArea(id: $id, adminLevel: $adminLevel, tolerance: $tolerance) {
    id
    name
    isoCode
    geometry
    adminLevel
    parentCode
  }
}
