query GetAdminAreas($adminLevel: Int!, $tolerance: Float) {
  adminAreas(adminLevel: $adminLevel, tolerance: $tolerance) {
    id
    name
    isoCode
    geometry
    adminLevel
    parentCode
  }
}
